const express = require('express')
const cors = require('cors')

const app = express()

//Cors
app.use(cors())


//Puerto 8080
const port = process.env.PORT || 3001

//Inicializa el servidor 3001
app.listen(port, () => {
    console.log("El servidor se inicia en el puerto " + port);
})
app.get('/superheroes', (req, res) => {
    res.json(
        [
        {
          name: "Iron Man",
          realName: "Tony Stark",
          height: 6.2,
          weight: 200,
          power: 100,
          intelligence: 100,
          speed: 100,
          strength: 100,
          agility: 100,
          durability: 100,
          energyProjection: 100,
          fightingSkills: 100,
        },
        {
          name: "Captain America",
          realName: "Steve Rogers",
          height: 6.2,
          weight: 200,
          power: 100,
          intelligence: 100,
          speed: 100,
          strength: 100,
          agility: 100,
          durability: 100,
          energyProjection: 100,
          fightingSkills: 100,
        },
        {
          name: "Thor",
          realName: "Thor Odinson",
          height: 6.2,
          weight: 200,
          power: 100,
          intelligence: 100,
          speed: 100,
          strength: 100,
          agility: 100,
          durability: 100,
          energyProjection: 100,
          fightingSkills: 100,
        },
        {
          name: "Hulk",
          realName: "Bruce Banner",
          height: 6.2,
          weight: 200,
          power: 100,
          intelligence: 100,
          speed: 100,
          strength: 100,
          agility: 100,
          durability: 100,
          energyProjection: 100,
          fightingSkills: 100,
        },
        {
          name: "Black Widow",
          realName: "Natasha Romanoff",
          height: 5.11,
          weight: 125,
          power: 100,
          intelligence: 100,
          speed: 100,
          strength: 100,
          agility: 100,
          durability: 100,
          energyProjection: 100,
          fightingSkills: 100,
        },
        {
          name: "Hawkeye",
          realName: "Clint Barton",
          height: 5.11,
          weight: 125,
          power: 100,
          intelligence: 100,
          speed: 100,
          strength: 100,
          agility: 100,
          durability: 100,
          energyProjection: 100,
          fightingSkills: 100,
        },
        {
          name: "Black Panther",
          realName: "T'Challa",
          height: 6.0,
          weight: 200,
          power: 100,
          intelligence: 100,
          speed: 100,
          strength: 100,
          agility: 100,
          durability: 100,
          energyProjection: 100,
          fightingSkills: 100,
        },
        {
          name: "Wolverine",
          realName: "James Howlett",
          height: 5.3,
          weight: 200,
          power: 100,
          intelligence: 100,
          speed: 100,
          strength: 100,
          agility: 100,
          durability: 100,
          energyProjection: 100,
          fightingSkills: 100,
        },
        {
          name: "Captain Marvel",
          realName: "Carol Danvers",
          height: 6.2,
          weight: 200,
          power: 100,
          intelligence: 100,
          speed: 100,
          strength: 100,
          agility: 100,
          durability: 100,
          energyProjection: 100,
          fightingSkills: 100,
        },
        {
          name: "Doctor Strange",
          realName: "Stephen Strange",
          height: 6.2,
          weight: 200,
          power: 100,
          intelligence: 100,
          speed: 100,
          strength: 100,
          agility: 100,
          durability: 100,
          energyProjection: 100,
          fightingSkills: 100,
        },
        {
          name: "Batman",
          realName: "Bruce Wayne",
          height: 6.2,
          weight: 200,
          power: 100,
          intelligence: 100,
          speed: 100,
          strength: 100,
          agility: 100,
          durability: 100,
          energyProjection: 100,
          fightingSkills: 100,
        },
        {
          name: "Superman",
          realName: "Clark Kent",
          height: 6.2,
          weight: 200,
          power: 100,
          intelligence: 100,
          speed: 100,
          strength: 100,
          agility: 100,
          durability: 100,
          energyProjection: 100,
          fightingSkills: 100,
        },
        {
          name: "Aquaman",
          realName: "Arthur Curry",
          height: 6.2,
          weight: 200,
          power: 100,
          intelligence: 100,
          speed: 100,
          strength: 100,
          agility: 100,
          durability: 100,
          energyProjection: 100,
          fightingSkills: 100,
        }
        ])
})